version: 2.1
orbs:
  node: circleci/node@1.1.0
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install mocha
            - run: alias mocha=' ./node_modules/.bin._mocha'
            - run: cd client && npm install
      - run:
          command:
            cd client && npm start
          background: true
      - run: cd client && npm run test
